### ISSUE TITLE
Ca marche que la moitié du temps (F-15E)

### ISSUE THREAD

**Issue by mechanick29** [docbrownd/ScratchpadPlus#1]
Quaand j'ajoute des waypoints, des fois il y a 2 ligne entre les lignes de waypoints. Et parfois, il y a des non saisies quand le logicielle saisie les coordonees. Je le demontre de le video. J'ai de mettre que une ligne entre les waypoints mais il y a les meme erreures. Bon boulot mais il quand meme beaucoup d'erreur. Tu me dit si c'est un erreur d'usage.
Video: [https://imgur.com/a/0zB7Aw6](https://imgur.com/a/0zB7Aw6)

**Comment by docbrownd** [comment]
> Quaand j'ajoute des waypoints, des fois il y a 2 ligne entre les lignes de waypoints. Et parfois, il y a des non saisies quand le logicielle saisie les coordonees. Je le demontre de le video. J'ai de mettre que une ligne entre les waypoints mais il y a les meme erreures. Bon boulot mais il quand meme beaucoup d'erreur. Tu me dit si c'est un erreur d'usage. Video: https://imgur.com/a/0zB7Aw6

le nombre de ligne vide entre chaque bloc n'a pas d'impact car seule les lignes avec une étoile sont lues pour l'insert. Pour les erreurs je pense que dans le cas présent le logiciel va trop vite, il faut saisir une valeurs plus importantes dans la selection "fps". Il faut que cette valeur soit supérieure aux fps que vous avez en jeu. Si vous avez 60-65, sélectionnez 70.
