### ISSUE TITLE
F/A 18C coordinates entering W instead of E 

### ISSUE THREAD

**Issue by Sting-Array** [docbrownd/ScratchpadPlus#3]
Hello - I have noticed that when entering coordinates for WPTS, the program is not entering E coordinates (even though they are correctly recorded in Scratchpad+). Instead, the script is trying to enter a W coordinate. This is despite all settings being correct (e.g. in Precise mode/no TAC page open, etc.). This might be user error (or a problem with a setting in DCS). However, loading coordinates for other platform (e.g. the F16) works perfectly. So, I am wondering if there might be an error in the script running the key presses? Thanks for looking into this. Regards. S

**Comment by docbrownd** [comment]
Hi, can you confirm you use last version ? 
also what is your fps in game and in scrachpad config ? (with F18 you need to config a little more in the software. example with 100fps in game, set 110fps on the interface.

**Comment by docbrownd** [comment]
i try with last version without problem. W instead E append when fps is set too low in regard of in game fps (so in fact scrachpad+ will press on the keyboard too quickly). be sure you set a value graeter that your true fps. 
best,

**Comment by Sting-Array** [comment]
Merci mille fois. I can confirm that I am using the latest version. I would never have thought to change FPS. I will make the recommended change and let you know if that solves the problem for me. Best wishes. S

**Comment by Sting-Array** [comment]
Bonjour Doc - I do not think that I have been making the correct adjustment as nothing I have done has corrected the error. To clarify, I have made a series of adjustments to the 'maximum FPS' settings, in DCS, under the 'system' tab. Those adjustments have ranged from setting the number as high as 300 (maximum) and as low as 100. In no case has the error caused by the rapid button presses been corrected. So, should I set an even lower maximum FPS in that setting? Or am I making changes in the wrong place? That is, is there another setting that I should be changing? Thanks for any further advice you might be able to provide when you have time to do so. Regards. S

**Comment by docbrownd** [comment]
when you set in scratchpad+ the fps value, set a value > that your IRL fps. more scratchpad+ fps is greater than IRL FPS, more press speed decrease (and not increase ^^). try with 150 for example. Don't change DCS params, only scratchpad+ config :

![image](https://github.com/user-attachments/assets/93ae5255-3f3c-4f16-bf29-619f33696b52)

**Comment by Sting-Array** [comment]
D’accord! Thanks again for taking the time to respond. I had not understood that the FOS functionality was in the app. Will try the solution you propose - and will let you know if this solves the problem (which I believe it will)!

**Comment by Sting-Array** [comment]
Merci beaucoup. Le problème est maintenant résolu. J'apprécie vraiment que vous preniez le temps de m'aider à résoudre ce problème. Meilleurs vœux. S

**Comment by docbrownd** [comment]
> Merci beaucoup. Le problème est maintenant résolu. J'apprécie vraiment que vous preniez le temps de m'aider à résoudre ce problème. Meilleurs vœux. S

pas de problème.

**Comment by docbrownd** [comment]
> Merci beaucoup. Le problème est maintenant résolu. J'apprécie vraiment que vous preniez le temps de m'aider à résoudre ce problème. Meilleurs vœux. S

pas de problème.
